name: "🚀 release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2
      - name: 🟢 node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: 🚀 publish
        uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: true
          check-version: true
          token: ${{ secrets.NPM_TOKEN }}
